
DROP TABLE IF EXISTS "SALAS";
DROP TABLE IF EXISTS "CLASIFICACIONES";
DROP TABLE IF EXISTS "FILAS";
DROP TABLE IF EXISTS "ASIENTOS";
DROP TABLE IF EXISTS "PELICULAS";
DROP TABLE IF EXISTS "FUNCION";

CREATE TABLE "SALAS" (
"IdSala" INTEGER
, "NombreSala" VARCHAR(100) not NULL
, PRIMARY KEY ("IdSala" AUTOINCREMENT)
);

CREATE TABLE "CLASIFICACIONES" (
"IdClasificacion" INTEGER
, "NombreClasificacion" VARCHAR(100) not NULL
, "Descripcion" VARCHAR(200)
, PRIMARY KEY ("IdClasificacion" AUTOINCREMENT)
);

CREATE TABLE "FILAS" (
"IdFila" INTEGER
, "NumeroFila" INTEGER not NULL
, "IdSala" INTEGER
, PRIMARY KEY ("IdFila" AUTOINCREMENT)
, FOREIGN KEY ("IdSala") REFERENCES SALAS ("IdSala")
);

CREATE TABLE "ASIENTOS" (
"IdAsiento" INTEGER
, "NumeroAsiento" INTEGER not NULL
, "IdFila" INTEGER
, PRIMARY KEY ("IdAsiento" AUTOINCREMENT)
, FOREIGN KEY ("IdFila") REFERENCES FILAS ("IdSala")
);

CREATE TABLE "PELICULAS" (
"IdPelicula" INTEGER
, "Titulo" VARCHAR(100) not NULL
, "Director" VARCHAR(100) not NULL
, "Genero"  VARCHAR(50) not NULL
, "Sinopsis" TEXT not NULL
, "Duracion" INTEGER not NULL
, "Eliminado" BOOLEAN not NULL DEFAULT 0
, "IdClasificacion" 
, PRIMARY KEY ("IdPelicula" AUTOINCREMENT)
, FOREIGN KEY ("IdClasificacion") REFERENCES CLASIFICACIONES ("IdClasificacion")
);

CREATE TABLE "FUNCION" (
"IdFuncion" INTEGER
, "IdPelicula" INTEGER not NULL
, "Fecha" date not NULL
, "HoraInicio"  VARCHAR(5) not NULL
, "HoraFin" VARCHAR(5) not NULL
, "IdSala" INTEGER not NULL
, "Eliminado" BOOLEAN not NULL DEFAULT 0
, PRIMARY KEY ("IdFuncion" AUTOINCREMENT)
, FOREIGN KEY ("IdPelicula") REFERENCES PELICULAS ("IdPelicula")
, FOREIGN KEY ("IdSala") REFERENCES SALAS ("IdSala")
);
